version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    user: root
    restart: always
    volumes:
      - /home/jenkins/lts-data/:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 18080:8080
      - 50000:50000
